[package]
name = "lox-macros"
version = "0.1.0"
authors = ["Lukas Kalbertodt <lukas.kalbertodt@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.19"
quote = "0.6"
syn = { version = "0.15", features = ["full", "extra-traits"] }
