[package]
name = "lox"
version = "0.1.0"
authors = ["Lukas Kalbertodt <lukas.kalbertodt@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "lox-cli",
    "benches/profiling",
]

[profile.release]
debug = true

[features]
default = ["io"]
large-handle = []
io = []

[dependencies]
ahash = "0.3.5"
boolinator = "2.4"
byteorder = "1.2"
cgmath = "0.17"
derive_more = "0.99"
failure = "0.1.2"
fxhash = "0.2"
lox-macros = { path = "lox-macros" }
num-traits = "0.2"
optional = "0.5"
smallvec = { version = "1.4.0", features = ["union"] }
stable-vec = "0.4"
static_assertions = "1.1.0"

[dev-dependencies]
color-backtrace = "0.4.2"
criterion = { version = "0.3", features = ["real_blackbox"] }
paste = "0.1"


# ----- Benchmarks -----------------------------------------------------------
[[bench]]
name = "io_ply"
harness = false

[[bench]]
name = "io_stl"
harness = false

[[bench]]
name = "mesh"
harness = false
