[package]
name = "lox"
version = "0.1.0"
authors = ["Lukas Kalbertodt <lukas.kalbertodt@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "lox-cli",
    "benches/profiling",
]

[profile.release]
debug = true

[dependencies]
boolinator = "2.4"
byteorder = "1.2"
cgmath = "0.17"
derive_more = "0.13"
failure = "0.1.2"
lox-macros = { path = "lox-macros" }
hashbrown = "0.1.3"
num-traits = "0.2"
smallvec = { version = "0.6", features = ["union"] }
stable-vec = { git = "https://github.com/LukasKalbertodt/stable-vec", branch = "v0.4-pre" }

[dev-dependencies]
criterion = { version = "0.2", features = ["real_blackbox"] }


# ----- Benchmarks -----------------------------------------------------------
[[bench]]
name = "io_ply"
harness = false

[[bench]]
name = "io_stl"
harness = false
