version: 2.1

executors:
  lox-ci:
    description: "A simple Ubuntu image with Rust installed (plus a few more things)"
    docker:
      - image: lukaskalbertodt/lox-ci:0.1
    working_directory: /repo

jobs:
  check_style:
    executor: lox-ci
    steps:
      - checkout
      - run: ./ci/check-basic-style.sh

  build:
    executor: lox-ci
    steps:
      - checkout
      - run: cargo generate-lockfile  # we need `Cargo.lock` to lookup the cache
      - restore_cache:
          # Try a cache with the same dependency graph first, but fall back to
          # any cache
          keys:
            - cargo-cache-{{ checksum "Cargo.lock" }}
            - cargo-cache-
      - run: cargo build --all
      - persist_to_workspace:
          root: /
          paths:
            - repo/
            - root/.cargo     # downloaded crates & crates.io index
      - save_cache:
          paths:
            - /root/.cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: cargo-cache-{{ checksum "Cargo.lock" }}

  test:
    executor: lox-ci
    steps:
      - attach_workspace:
          at: /
      - run: cargo test --all

workflows:
  version: 2.1
  main:
    jobs:
      - check_style
      - build
      - test:
          requires:
            - build
