[package]
name = "loxi"
version = "0.1.0"
authors = ["Lukas Kalbertodt <lukas.kalbertodt@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
failure = "0.1"
lox = { path = "../" }
structopt = "0.3"
term-painter = "0.2"
term_size = "0.3"
