name: CI

on:
  pull_request:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  style:
    name: Check basic style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: LukasKalbertodt/check-basic-style@v0.1
      with:
        files: |
          **/*.{toml,rs}

  check:
    name: 'Build, test & document'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Restore cache
      uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build --all --lib --bins
    - name: Build Examples
      run: cargo build --examples
    - name: Build Benchmarks
      run: cargo build --benches
    - name: Run tests (default features)
      run: cargo test --all
    - name: Run tests ('large-handle' feature)
      run: cargo test --all --features="large-handle"
    - name: Run tests (no default features)
      run: |
        cargo test --lib --no-default-features
        cargo test --doc --no-default-features
    - name: Generate documenation
      run: cargo doc --no-deps
